ALTER TABLE ARROW ADD COLUMN tip_weight TEXT DEFAULT '';
ALTER TABLE PASSE ADD COLUMN exact INTEGER DEFAULT 0;
UPDATE PASSE SET exact=1 WHERE _id IN (SELECT DISTINCT p._id FROM PASSE p, SHOOT s WHERE p._id=s.passe AND s.x!=0);
