CREATE TEMP TABLE IF NOT EXISTS DAIR_TRANSLATION AS
SELECT  sr._id
FROM STANDARD_ROUND_TEMPLATE sr
WHERE sr._id>198
AND sr.club<256
AND sr.name='DAIR 380';
CREATE TEMP TABLE IF NOT EXISTS SR_TRANSLATION AS
SELECT  sr._id AS fromSR, (4+sr._id-(SELECT MAX(tr._id) FROM DAIR_TRANSLATION tr WHERE tr._id-4<sr._id)) AS toSR
FROM STANDARD_ROUND_TEMPLATE sr
WHERE sr._id>198
AND sr.club<256;
CREATE TEMP TABLE IF NOT EXISTS R_TRANSLATION AS
SELECT  r1._id AS fromR, r2._id AS toR
FROM ROUND_TEMPLATE r1, ROUND_TEMPLATE r2, SR_TRANSLATION sr
WHERE r1.sid=sr.fromSR
AND r2.sid=sr.toSR
AND r1.r_index=r2.r_index;
UPDATE ROUND
SET template = (SELECT toR
  FROM R_TRANSLATION
  WHERE fromR=template)
WHERE template IN (SELECT fromR FROM R_TRANSLATION);
UPDATE TRAINING
SET standard_round = (SELECT toSR
  FROM SR_TRANSLATION
  WHERE fromSR=standard_round)
  WHERE standard_round IN (SELECT fromSR FROM SR_TRANSLATION);
DELETE FROM STANDARD_ROUND_TEMPLATE
WHERE _id IN (SELECT fromSR FROM SR_TRANSLATION);
DELETE FROM ROUND_TEMPLATE
WHERE _id IN (SELECT fromR FROM R_TRANSLATION);
DROP TABLE DAIR_TRANSLATION;
DROP TABLE SR_TRANSLATION;
DROP TABLE R_TRANSLATION;
