DELETE FROM ROUND WHERE _id IN (SELECT r._id FROM ROUND r LEFT JOIN TRAINING t ON t._id=r.training WHERE t._id IS NULL);
DELETE FROM PASSE WHERE _id IN (SELECT p._id FROM PASSE p LEFT JOIN ROUND r ON r._id=p.round WHERE r._id IS NULL);
DELETE FROM SHOOT WHERE _id IN (SELECT s._id FROM SHOOT s LEFT JOIN PASSE p ON p._id=s.passe WHERE p._id IS NULL);
